// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://zrqfnautqywrgowwbtnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpycWZuYXV0cXl3cmdvd3didG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NjIwMTIsImV4cCI6MjA3OTMzODAxMn0.SG0sFBtUyLRawdfd9DxlRM21E6GUrkWyIHpCDY1ECOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
